--liquibase formatted sql
--changeset dev:202503301945
--comment: board_column table create
CREATE TABLE BOARD_COLUMN (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    `ORDER` INT NOT NULL,
    KIND VARCHAR(10) NOT NULL,
    BOARD_ID BIGINT NOT NULL,
    CONSTRAINT FK_BOARD_ID FOREIGN KEY (BOARD_ID) REFERENCES BOARD (ID) ON DELETE CASCADE,
    CONSTRAINT UK_ORDER_ID UNIQUE KEY UNIQUE_BOARD_ID_ORDER (BOARD_ID, `ORDER`)
) ENGINE=InnoDB;
--rollback DROP TABLE BOARD_COLUMN