--liquibase formatted sql
--changeset dev:202503301924
--comment: board table create
CREATE TABLE BOARD (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    USER_ID BIGINT NOT NULL,
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON DELETE CASCADE
) ENGINE=InnoDB;
--rollback DROP TABLE BOARD